FROM python:3.11-slim
WORKDIR /app

#intall dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#Copy application files
COPY . .
#creat log directory
RUN mkdir -p /var/logs/app

EXPOSE 5000

CMD [ "python","banking_app.py" ]